name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Test Backend Image
      run: |
        docker build -t shop-server ./shop-server
        docker run --rm shop-server java -version

    - name: Build and Test Frontend Image
      run: |
        docker build -t shop-client ./shop-client
        docker run --rm shop-client node -v

    - name: Validate Docker Compose
      run: docker-compose -f docker-compose.yml config

    - name: Start Services with Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for Services to Start
      run: sleep 30

    - name: Check API Health
      run: curl -f http://localhost:8080/actuator/health

    - name: Stop and Cleanup Services
      run: docker-compose -f docker-compose.yml down
